<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250506084142 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE review ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE review ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE tag ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE tag ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "user" ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE video_game ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE video_game ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE video_game ALTER release_date TYPE DATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE video_game ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN video_game.release_date IS ''
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN video_game.updated_at IS ''
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE review ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE review ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "tag" ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "tag" ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "user" ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "user" ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE video_game ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE video_game ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE video_game ALTER release_date TYPE DATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE video_game ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN video_game.release_date IS '(DC2Type:date_immutable)'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN video_game.updated_at IS '(DC2Type:datetime_immutable)'
        SQL);
    }
}
